# SPDX-License-Identifier: BSD-3-Clause
# musl-based image (Alpine) — works on amd64 and arm64

FROM azul/zulu-openjdk-alpine:17-jre

WORKDIR /app

COPY lib/ lib/
COPY SmokeTest.class .
COPY log4j2.xml .

CMD ["java", "-cp", ".:lib/*", "SmokeTest"]
