# SPDX-License-Identifier: BSD-3-Clause
# musl-based image (Alpine) — works on amd64 and arm64

ARG JDK_VER=17
FROM azul/zulu-openjdk-alpine:${JDK_VER}-jre

WORKDIR /app

COPY lib/ lib/
COPY SmokeTest.class .
COPY log4j2.xml .

CMD ["java", "--enable-native-access=ALL-UNNAMED", "-cp", ".:lib/*", "SmokeTest"]
